//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Inventory_Management_System
{
    using System;
    using System.Collections.Generic;

    public partial class user
    {
        [Key]
        public int u_id { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Name is required!")]
        public string u_name { get; set; }

        [Display(Name = "Username")]
        [Required(ErrorMessage = "Username is required!")]
        public string u_username { get; set; }

        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required!")]
        public string u_password { get; set; }

        [Display(Name = "Phone #")]
        [Required(ErrorMessage = "Phone # is required!")]
        public string u_phone { get; set; }

        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email is required!")]
        public string u_email { get; set; }

        [Display(Name = "Status")]
        [Required(ErrorMessage = "Status is required!")]
        public byte u_status { get; set; }

        [Display(Name = "Role")]
        [Required(ErrorMessage = "Role is required!")]
        public byte u_roleID { get; set; }

        public virtual role role { get; set; }
    }
}
